### ISSUE TITLE
Bone marrow data (Hammersmith Registry)

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#60]
In **Baseline>Bone marrow data** Bone marrow aspirate available, Bone marrow trephine available, Immunophenotype on BM available should all be blank. Currently they are set to No (record 247).

![image](https://github.com/fhosking/cml-database/assets/169662104/a7a78705-93a2-4ba5-bee5-eb863e79e3e8)

**Comment by fhosking** [comment]
There are a number of places across the registry where tickboxes have been converted into yes/no questions. In a sense, it is more accurate. Is it the case in the above example that the Bone marrow trephine was available? If 'no', wouldn't it be accurate to record the result as 'no' rather than blank?

**Comment by afzalkhan500** [comment]
Agree that all tick boxes should be yes or no. Blank tick in this case means no.
