### ISSUE TITLE
🚨 Hammersmith Registry/TKIs after allo BMT CT

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#70]
Clicking yes to “TKIs after allo BMT CT” should then allow entry of “Which TKI post-AlloSCT” just below and not in a separate section and the options should be as shown in table below:

![image](https://github.com/user-attachments/assets/f725cb9b-a2eb-4388-97b9-39aa74dce154)

1 | Imatinib
2 | Dasatinib
3 | Nilotinib
4 | Bosutinib
5 | Ponatinib
6 | None
7 | ABL001 (Asciminib)

**Comment by afzalkhan500** [comment]
“TKIs after allo BMT CT” should be “TKIs after alloSCT”

**Comment by fhosking** [comment]
I see the issue. Technically, there is a difficulty because there are multiple responses of "Which TKI post-AlloSCT" from the single question “TKIs after allo BMT CT”. So we need a mechanism to allow users to cleanly add multiple lines. Currently, this is attempted by cleanly separating them out into their own blocks. We could perhaps instead add a 'Number of TKIs after ...' or simply merge the multiple blocks into the main block, retaining the 'Add new TKI' buttons. Do you feel that you have a preference?

**Comment by fhosking** [comment]
I have split Auto, Allo and DLI in to their own sections. I'm hoping this resolves the primary issues with the form.

<img width="580" alt="image" src="https://github.com/user-attachments/assets/3bdcc9bf-77d6-49f5-84db-e11a65f3f551">
